environment:
  matrix:
    - nodejs_version: '8'
    - nodejs_version: '6'
install:
  - ps: Install-Product node $env:nodejs_version
  - set PATH=%APPDATA%\npm;%PATH%
  - set CI=true
  - npm cache verify
  - npm config set progress=false
  - npm i npm@latest -g
  - node --version
  - npm --version
  - npm install
build: off
version: '{build}'
test_script:
  - npm test
after_test:
  - npm run codecov
  - npm run nsp
